#!/bin/bash

export PATH="$PATH:$HOME/.cargo/bin:\
$HOME/.local/bin:\
$HOME/.local/scripts:\
$HOME/.local/nvim-linux64/bin"

# vim/nvim
if command -v nvim &>/dev/null; then
    export EDITOR=nvim
    alias \
        vi="nvim" \
        vh="cd ~/.config/nvim"
elif command -v vim &>/dev/null; then
    export EDITOR=vim
    alias \
        vi="vim" \
        vh="cd ~/.vim"
fi
alias vimdiff="vi -d"

# bat
command -v bat &> /dev/null && \
    alias \
        bcat="/usr/bin/cat" \
        bathelp='bat --plain --language=help' \
        vat="bat" \
        pat="bat --style=plain" \
        cat="bat --style=changes" \
        sat="pat --paging=never" \
        aat="bat -A" \
        less="cat"
tlr() { tldr "$1" | bat --plain -l="md"; }
bh() { "$@" --help 2>&1 | bathelp; }

# eza/ls
alias bls="/usr/bin/ls" lsr="realpath"
if [[ $USE_LSD -eq 1 ]]; then
    alias \
        els="bls -hN --color=auto --group-directories-first" \
        ls="lsd --group-directories-first" \
        l="ls --icon never" \
        la='ls -A' \
        ll='ls -l' \
        lal='lal -Al'
    command -v eza >/dev/null && alias tree='eza --tree'
elif command -v eza &> /dev/null; then
    alias \
        els="bls -hN --color=auto --group-directories-first" \
        l='eza --group-directories-first' \
        ls="l -F" \
        ls1="ls -1" \
        la='l -a' \
        ll='l -l' \
        lal='l -al' \
        tree='eza --tree'
else
    alias \
        l="ls -hN --color=auto --group-directories-first" \
        ls='l -CF' \
        ls1="ls -1" \
        la='l -A' \
        ll='l -l' \
        lal='l -Al'
fi
pree() { tree "$1" | cat; }

# git
qcom() {
    if [ -z "$1" ]; then
        git add . && git commit -m 'automated quick commit'
    else
        git add . && git commit -m "$1"
    fi
}
qcomp() {
    qcom "$@" && git push || \
        git  push --set-upstream origin "$(git rev-parse --abbrev-ref HEAD)";
};
alias gt="git status" \
    gp="git pull" \
    gd="git diff" \
    gr="git restore" \
    gg="git grep" \
    gcm="git commit" \
    gclean="git clean -fdx"

# apt
lill () {
  for prog in "${@}"; do
    if ! command -v "${prog}" &>/dev/null; then
      echo "Installing ${prog}"...
      sudo apt-get install -y "${prog}"
    fi
  done
}
alias apt="apt-get" \
    whichv="apt-cache policy"


# trash
command -v trash &> /dev/null && \
    alias rm="trash" || \
    alias rm="rm -I"; alias vrm="rm -Iv"

# yt-dlp
alias \
    yt="yt-dlp  -i -o '%(title)s.%(ext)s'" \
    yts="yt-dlp --embed-subs -i -o '%(title)s.%(ext)s'" \
    yta="yt -x -f bestaudio/best --audio-format mp3"
ytq() {
    [ -z "$2" ] && QUAL="1080" || QUAL=$2
    yt -f "bv*[height<=${QUAL}]+ba/b[height<=${QUAL}] / wv*+ba/w" "$1"
}

unarchive() {
    case "$1" in
        *.zip) unzip "$1" ;;
        *.tar.gz) tar -xzvf "$1" ;;
        *.tar.bz2) tar -xjvf "$1" ;;
        *.tar) tar -xvf "$1" ;;
        *) echo "Unsupported format" ;;
    esac
}

# sane defaults, i.e. colors and verbosity
alias \
    grep='grep --color=auto' \
    fgrep='fgrep --color=auto' \
    egrep='egrep --color=auto' \
    ip="ip -color=auto" \
    diff="diff --color=auto" \
    mv="mv -i" \
    rsync="rsync -vrPlu" \
    cp="cp -i" \
    ffmpeg="ffmpeg -hide_banner" \
    bc="bc -ql"

# shortcuts
#
update_all() {
    echo -n -e "\n>APT\n"
    sudo apt-get update
    sudo apt-get upgrade -y --allow-downgrades
    echo -n -e "\n>PIPX\n"
    pipx upgrade-all
    echo -n -e "\n>CARGO\n"
    cargo install-update -a
}
cht() { curl cheat.sh/"$1" | less; }
mkcd() { mkdir "$1" && cd "$1" || exit; }
ct() { python3 <(echo "import random; ct=random.randint(0,1); s='heads' if ct else 'tails'; print(s)"); }
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error) $(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias \
    ua="update_all" \
    mkd="mkdir -pv" \
    myip="curl ipinfo.io/ip" \
    xo="xdg-open" \
    kas="tmux kill-ses -a"
alias \
    zshrc="\${EDITOR} ~/.zshrc" \
    rezsh="source ~/.zshrc" \
    rebash="source ~/.bashrc" \
    bashrc="\${EDITOR} ~/.bashrc" \
    aliasrc="\${EDITOR} ~/.config/aliasrc" \
    locrc="\${EDITOR} ~/.config/localshrc"
alias \
    visc="vi ~/notes/keymaps/vi.md" \
    susc="vi ~/notes/keymaps/su.md"

# development-specific
qcr() { gcc "$@" -o tmp.out && ./tmp.out ; rm tmp.out > /dev/null; };
p4u() { picocom -b 115200 "/dev/ttyUSB${1}"; }
p4a() { picocom -b 115200 "/dev/ttyACM${1}"; }
alias \
    make="make -j\$((\$(nproc) - 2))" \
    p3="python3" \
    sven="source venv/bin/activate"

# remap caps lock and escape on tty sessions
caps2esc() {
    echo -e "keycode 1 = Caps_Lock \nkeycode 58 = Escape" > /tmp/caps2esc
    sudo loadkeys /tmp/caps2esc
}
back2caps() {
    echo -e "keycode 58 = Caps_Lock \nkeycode 1 = Escape" > /tmp/back2caps
    sudo loadkeys /tmp/back2caps
}

lfip() { kitty _lfip "$@"; }
lfcd() { cd "$(command lf -print-last-dir "$@")" || exit; }

# tokyonight-night theme for fzf
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--color=fg:#c0caf5,bg:#1a1b26,hl:#ff9e64 \
--color=fg+:#c0caf5,bg+:#292e42,hl+:#ff9e64 \
--color=info:#7aa2f7,prompt:#7dcfff,pointer:#7dcfff \
--color=marker:#9ece6a,spinner:#9ece6a,header:#9ece6a"
