# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# UBUNTU 20.04/22.04 DEFAULTS: If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

FORCE_PROMPT_COLOR=

# set up the prompt
case "$TERM" in
    tmux|*xterm-color|*-256color|*"$FORCE_PROMPT_COLOR"*)
        export PS1="\[\033[01;34m\]\n\w\n\[\033[01;32m\]\$\[\033[00m\] "
        ;;
    *)
        export PS1="\n\w\n\$ "
        ;;
esac

## use lf to switch directories and bind it to ctrl-o
lfcd() {
  tmp="$(mktemp)"
  lf -last-dir-path="$tmp" "$@"
  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp" &> /dev/null
    [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
  fi
}
bind '"\C-o":"lfcd\C-m"'

#
# UBUNTU 20.04/22.04 DEFAULTS (without the prompt settings)
#
# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
# End of Ubuntu 20.04 defaults

# configure PATH
export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$HOME/.local/scripts:$HOME/bin:$PATH

# load aliases and shortcuts if existent
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"
[ -f "$HOME/.config/localshrc" ] && source "$HOME/.config/localshrc"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
eval "$(zoxide init bash)"
. "$HOME/.cargo/env"
