# DEFAULTS: If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# set up the prompt
FORCE_PROMPT_COLOR=
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null || \
    [[ $FORCE_COLOR_PROMPT -eq 1 ]]; then
    export PS1="\[\033[01;34m\]\n\w\n\[\033[01;32m\]\$\[\033[00m\] "
else
    export PS1="\n\w\n\$ "
fi

# zoxide
if command -v zoxide &> /dev/null; then
    eval "$(zoxide init bash)"
    alias bcd="\cd" cd="z"
fi
bind '"\C-o":"lfcd\C-m"'

#
# DEFAULTS
#
# don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
# End of Ubuntu 20.04 defaults

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -f "$HOME/.config/localshrc" ] && source "$HOME/.config/localshrc"
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"
[ -f "$HOME/.config/lessrc" ] && source "$HOME/.config/lessrc"

[ -f "$HOME/.local/scripts/lfcd.sh" ] && source "$HOME/.local/scripts/lfcd.sh"
bind '"\C-o":"lfcd\C-m"'
bind '"\C-p":"lfcd\C-m"'
