## basic settings

# disable ctrl-s to freeze terminal
stty stop undef
# enable bash-style comments
setopt interactivecomments

# history
setopt sharehistory
HISTSIZE=1000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# vi mode
bindkey -v
export KEYTIMEOUT=1

# change cursor shape for different vi modes
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # use beam shape cursor on startup
preexec() { echo -ne '\e[5 q' ;} # use beam shape cursor for each new prompt

# basic auto/tab complete
autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
_comp_options+=(globdots) # include hidden files.
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
compinit

# pure prompt
fpath+=($HOME/.config/zsh/pure)
autoload -U promptinit; promptinit

prompt pure
PURE_PROMPT_SYMBOL=$
PURE_PROMPT_VICMD_SYMBOL=V

# configure PATH and similar variables
export JAVA_HOME=~/.jdks
export PATH="$PATH:"\
"$HOME/.cargo/bin:"\
"$HOME/.local/bin:"\
"$JAVA_HOME/openjdk-20.0.1/bin:"\
"/usr/local/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin"

## bindings

# reverse search
bindkey '^R' history-incremental-search-backward

# edit line in vim with ctrl+e
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

bindkey -M menuselect "\H" vi-backward-char
bindkey -M menuselect "\K" vi-up-line-or-history
bindkey -M menuselect "\L" vi-forward-char
bindkey -M menuselect "\J" vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# use lf to switch directories and bind it to ctrl-o
eval "$(zoxide init zsh)"
lfcd() {
  tmp="$(mktemp)"
  lf -last-dir-path="$tmp" "$@"
  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp" &> /dev/null
    [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
  fi
}
bindkey -s '^o' 'lfcd\n'

# bind ctrl + arrow right/left arrow keys to forward-word/backward word
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

## sourcing other files

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"
[ -f "$HOME/.config/localshrc" ] && source "$HOME/.config/localshrc"
