#!/usr/bin/bash

if [[ -n $EXT_PKGM ]]; then
    pkgm=$EXT_PKGM
elif command -v apt &> /dev/null; then
    pkgm="sudo apt-get install -y"
else
    echo "Failed to setup the 'pkgm' variable. Exiting..."
    exit 1
fi

_ill () {
    if command -v ${!#} &> /dev/null; then
        echo "${!#} already installed. Skipping..."
    elif  [[ $SKIP_LIST == "*${!#}*" ]]; then
        "${!#} in skip list. Skipping..."
    else
        echo "Attempting to install ${!#}..."
        $@ >/dev/null && echo "${!#} installed."
    fi
}

ill () {
    if [[ $1 == *" "* ]]; then
        pkgs=($1)
        for pkg in "${pkgs[@]}"; do
            _ill $pkgm $pkg
        done
    else
        for pkg in $@; do
            _ill $pkgm $pkg
        done
    fi
}
