set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

"" Plugins
if ! filereadable(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/plug.vim"'))
	echo "Downloading junegunn/vim-plug to manage plugins..."
	silent !mkdir -p ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/
	silent !curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" > ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/plug.vim
	autocmd VimEnter * PlugInstall
endif

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-surround'
Plug 'vimwiki/vimwiki'
Plug 'preservim/nerdtree'
Plug 'machakann/vim-highlightedyank'
call plug#end()

" Disable vertical line at max string length in NERDTree
autocmd FileType * setlocal colorcolumn=+1
autocmd FileType nerdtree setlocal colorcolumn=""

"" Basics
set backspace=indent,eol,start
set spell spelllang=en_us,pl
set termguicolors
set encoding=utf-8
filetype plugin on
set number relativenumber

"" Others
" Have the prompt 5 lines above the file ends when scrolling
set scrolloff=5
" split tabs at the bottom and on the right
set splitbelow splitright
" ctrl+n autocompletion
set wildmode=longest,list,full
" Enable line wrapping
set wrap linebreak
" Highlight search results
set hlsearch
" Enable incremental searching
set incsearch
" Enable smart case searching
set smartcase


" Enable the use of the leader key
let mapleader = ","

" Source .vimrc/init.vim
nnoremap <leader>sv :source $MYVIMRC<CR>

" Don't use Ex mode, use Q for formatting.
map Q gq
set textwidth=80

" highlight column right after max text width
set colorcolumn=81                                                            
hi ColorColumn ctermbg=lightgrey guibg=lightgrey

" Comfy ctrl+c/ctrl+v
vnoremap <C-c> "+y
map <C-v> "+p

" For faster hjkl-ing around and stuff
set ttimeoutlen=50


