source ~/.vim/plugins.vim
source ~/.vim/remaps.vim

" Neovim defaults
set nocompatible
set autoindent
set showcmd
set autoread
set backspace=indent,eol,start
set belloff=all
set encoding=utf-8
set ruler
set ttimeoutlen=50
set hlsearch
set incsearch
set history=10000
set formatoptions=tcqj

" Indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent

" Interface
set colorcolumn=81
set mouse=a
set smartcase
set nonumber
set ignorecase
set splitbelow
set splitright
set nowrap
set scrolloff=5

set updatetime=1000
set textwidth=0
set wildmode=longest,list,full
set spelllang=en_us
set spell
set spellsuggest=best,9
set conceallevel=0

" Theme
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
set notermguicolors
colorscheme industry
hi ColorColumn ctermbg=lightgrey guibg=lightgrey
hi clear SpellBad
hi clear SpellLocal
hi clear SpellRare
hi clear SpellCap
hi SpellBad cterm=underline

" Retain cursor position
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

" Delete all trailing white-space and end of file newlines
autocmd BufWritePre * let currPos = getpos(".")
	autocmd BufWritePre * %s/\s\+$//e
	autocmd BufWritePre * %s/\n\+\%$//e
