#!/usr/bin/bash

_lfip() {
    if [  ! -e /tmp/lfrc ]; then
        cp -f ~/.config/lf/lfrc /tmp/lfrc
        echo "set previewer ~/.config/lf/lf_kitty_preview" >> /tmp/lfrc
        echo "set cleaner ~/.config/lf/lf_kitty_clean" >> /tmp/lfrc
    fi
}
lfcd -config /tmp/lfrc
