#!/usr/bin/bash

ill() {

  for prog in "${@}"; do
    if ! command -v "${prog}" &>/dev/null; then
      echo "Installing ${prog}"...
      sudo apt-get install -y "${prog}" >/dev/null
    fi
  done
}
