#!/usr/bin/bash

if [[ -n $EXT_PKGM ]]; then
    pkgm=$EXT_PKGM
elif command -v apt &> /dev/null; then
    pkgm="sudo apt-get install -y"
else
    distro=$(uname -v)
    if [[ $distro == "SMP PREEMPT" ]]; then
        pkgm="pkg install"
    else
        echo "Failed to setup the 'pkgm' variable. Exiting..."
        exit 1
    fi
fi

_ill () {
    if command -v ${!#}; then
        echo "${!#} already installed. Skipping..."
    elif  [[ $SKIP_LIST == "*${!#}*" ]]; then
        echo "${!#} in skip list. Skipping..."
    else
        echo "Attempting to install ${!#}..."
        echo $@ || "Failed to install ${!#}."
    fi
}

ill () {
    if [[ $1 == *" "* ]]; then
        for pkg in "$1"; do
            _ill $pkgm $pkg
        done
    else
        for pkg in $@; do
            _ill $pkgm $pkg
        done
    fi
}
