#!/usr/bin/bash

distro=$(uname -v)
if [[ $distro == "Debian|Ubuntu" ]]; then
    pkgm="apt-get install"
elif [[ $distro == "SMP PREEMPT" ]]; then
    pkgm="pkg install"
fi

_ill () {
    if ! command -v $2; then
        echo "Installing $2..."
        sudo $1 -y $2
    fi
}

# ill foo bar
ill () {
    if [[ $1 == *" "* ]]; then
        for pkg in "$1"; do
            _ill $pkgm $pkg
        done
    else
        for pkg in $@; do
            _ill $pkgm $pkg
        done
    fi
}
