# start with tmux if appropriate
if  command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] \
    && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  exec tmux
fi

# defaults exports 
command -v nvim &> /dev/null && export EDITOR=nvim
command -v alacritty &> /dev/null && export TERMINAL=alacritty

# history
setopt histignorealldups sharehistory
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# vi mode
bindkey -v
export KEYTIMEOUT=1

# change cursor shape for different vi modes
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap 
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # use beam shape cursor on startup
preexec() { echo -ne '\e[5 q' ;} # use beam shape cursor for each new prompt

# basic auto/tab complete
autoload -Uz compinit 
zstyle ':completion:*' menu select
zmodload zsh/complist
_comp_options+=(globdots) # include hidden files.
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
compinit

# pure prompt 
fpath+=($HOME/.config/zsh/pure)
autoload -U promptinit; promptinit

PURE_PROMPT_SYMBOL="$"
PURE_PROMPT_VICMD_SYMBOL="%%"
zstyle :prompt:pure:path color cyan
zstyle ':prompt:pure:prompt:*' color '#FFAA00'
zstyle :prompt:pure:suspended_jobs color '#FFAA00'

prompt pure

# load aliases and shortcuts if existent
[ -f "$HOME/.config/aliasrc" ] && source "$HOME/.config/aliasrc"
[ -f "$HOME/.config/shortcutrc" ] && source "$HOME/.config/shortcutrc"
